/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 06-Aug-2020 10:13:40 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS "config"."execution_id_seq" CASCADE
;

/* Drop Tables */

DROP TABLE IF EXISTS "config"."execution" CASCADE
;

/* Create Tables */

CREATE TABLE "config"."execution"
(
	"id" serial NOT NULL,
	"name" varchar(50)	 NOT NULL,
	"description" varchar(100)	 NULL,
	"in_use" boolean NOT NULL DEFAULT 't'
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "config"."execution" ADD CONSTRAINT "execution_pkey"
	PRIMARY KEY ("id")
;

ALTER TABLE "config"."execution" ADD CONSTRAINT "execution_name_key" UNIQUE ("name")
;