/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 06-Aug-2020 10:13:38 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS "lookup"."country_id_seq" CASCADE
;

/* Drop Tables */

DROP TABLE IF EXISTS "lookup"."country" CASCADE
;

/* Create Tables */

CREATE TABLE "lookup"."country"
(
	"country" varchar(10)	 NOT NULL,
	"region" text NULL,
	"id" serial NOT NULL
)
;
/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "lookup"."country" ADD CONSTRAINT "country_pkey"
	PRIMARY KEY ("id")
;

ALTER TABLE "lookup"."country" ADD CONSTRAINT "country_country_key" UNIQUE ("country")
;