/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 06-Aug-2020 10:13:39 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS "lookup"."source_id_seq" CASCADE
;

/* Drop Tables */

DROP TABLE IF EXISTS "lookup"."source" CASCADE
;

/* Create Tables */

CREATE TABLE "lookup"."source"
(
	"id" serial NOT NULL,
	"source" varchar(50)	 NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "lookup"."source" ADD CONSTRAINT "source_pkey"
	PRIMARY KEY ("id")
;

ALTER TABLE "lookup"."source" ADD CONSTRAINT "source_source_key" UNIQUE ("source")
;