/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 06-Aug-2020 10:13:39 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS "fund"."fund_id_seq" CASCADE
;

/* Drop Tables */

DROP TABLE IF EXISTS "fund"."fund" CASCADE
;

/* Create Tables */

CREATE TABLE "fund"."fund"
(
	"id" serial NOT NULL,
	"name" varchar(100)	 NOT NULL,
	"currency_id" integer NOT NULL,
	"execution_state_id" integer NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "fund"."fund" ADD CONSTRAINT "fund_pkey"
	PRIMARY KEY ("id")
;

ALTER TABLE "fund"."fund" ADD CONSTRAINT "fund_name_key" UNIQUE ("name")
;

/* Create Foreign Key Constraints */

ALTER TABLE "fund"."fund" ADD CONSTRAINT "fund_currency_fkey"
	FOREIGN KEY ("currency_id") REFERENCES "lookup"."currency" ("id") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "fund"."fund" ADD CONSTRAINT "fund_execution_state_fkey"
	FOREIGN KEY ("execution_state_id") REFERENCES "config"."execution_state" ("id") ON DELETE No Action ON UPDATE No Action
;