INSERT INTO lookup.country(country, region)
VALUES
  ('CN', 'Asia ex JP'),
  ('HK', 'Asia ex JP'),
  ('ID', 'Asia ex JP'),
  ('IN', 'Asia ex JP'),
  ('KR', 'Asia ex JP'),
  ('MY', 'Asia ex JP'),
  ('PH', 'Asia ex JP'),
  ('SG', 'Asia ex JP'),
  ('TH', 'Asia ex JP'),
  ('TW', 'Asia ex JP'),
  ('EG', 'CEEMEA'),
  ('HU', 'CEEMEA'),
  ('IL', 'CEEMEA'),
  ('NG', 'CEEMEA'),
  ('PL', 'CEEMEA'),
  ('RO', 'CEEMEA'),
  ('RU', 'CEEMEA'),
  ('TR', 'CEEMEA'),
  ('ZA', 'CEEMEA'),
  ('CH', 'Europe ex UK'),
  ('CZ', 'Europe ex UK'),
  ('DE', 'Europe ex UK'),
  ('EU', 'Europe ex UK'),
  ('FR', 'Europe ex UK'),
  ('NO', 'Europe ex UK'),
  ('SE', 'Europe ex UK'),
  ('MULT', 'Global'),
  ('JP', 'Japan'),
  ('AR', 'Latam'),
  ('BR', 'Latam'),
  ('CL', 'Latam'),
  ('CO', 'Latam'),
  ('MX', 'Latam'),
  ('PE', 'Latam'),
  ('CA', 'North America'),
  ('US', 'North America'),
  ('AU', 'Pacific'),
  ('NZ', 'Pacific'),
  ('GB', 'United Kingdom')
ON CONFLICT Do NOTHING
;
