/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 06-Aug-2020 10:13:38 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS "lookup"."currency_id_seq" CASCADE
;

/* Drop Tables */

DROP TABLE IF EXISTS "lookup"."currency" CASCADE
;

/* Create Tables */

CREATE TABLE "lookup"."currency"
(
	"id" serial NOT NULL,
	"currency" char(3)	 NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "lookup"."currency" ADD CONSTRAINT "currency_pkey"
	PRIMARY KEY ("id")
;

ALTER TABLE "lookup"."currency" ADD CONSTRAINT "currency_currency_key" UNIQUE ("currency")
;