/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 06-Aug-2020 10:13:38 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS "asset"."asset_group_id_seq" CASCADE
;

/* Drop Tables */

DROP TABLE IF EXISTS "asset"."asset_group" CASCADE
;

/* Create Tables */

CREATE TABLE "asset"."asset_group"
(
	"id" serial NOT NULL,
	"category" text NOT NULL,
	"execution_state_id" integer NULL,
	"subcategory" text NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "asset"."asset_group" ADD CONSTRAINT "asset_group_pkey"
	PRIMARY KEY ("id")
;

ALTER TABLE "asset"."asset_group" ADD CONSTRAINT "asset_group_category_subcategory_key"
	UNIQUE (category, subcategory)
;

/* Create Foreign Key Constraints */
ALTER TABLE "asset"."asset_group" ADD CONSTRAINT "asset_group_execution_state_fkey"
	FOREIGN KEY ("execution_state_id") REFERENCES "config"."execution_state" ("id") ON DELETE No Action ON UPDATE No Action
;