/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 06-Aug-2020 10:13:38 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS "config"."asset_analytic_id_seq" CASCADE
;

/* Drop Tables */

DROP TABLE IF EXISTS "config"."asset_analytic" CASCADE
;

/* Create Tables */

CREATE TABLE "config"."asset_analytic"
(
	"id" serial NOT NULL,
  "ticker" text NOT NULL,
	"categories" text[]	 NOT NULL,
	"execution_state_id" integer NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "config"."asset_analytic" ADD CONSTRAINT "asset_analytic_pkey"
	PRIMARY KEY ("id")
;

ALTER TABLE "config"."asset_analytic" ADD CONSTRAINT "asset_analytic_ticker_key" UNIQUE ("ticker")
;

/* Create Foreign Key Constraints */

ALTER TABLE "config"."asset_analytic" ADD CONSTRAINT "asset_analytic_execution_state_fkey"
	FOREIGN KEY ("execution_state_id") REFERENCES "config"."execution_state" ("id") ON DELETE No Action ON UPDATE No Action
;