/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 06-Aug-2020 10:13:40 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS "config"."execution_state_id_seq" CASCADE
;

/* Drop Tables */

DROP TABLE IF EXISTS "config"."execution_state" CASCADE
;

/* Create Tables */

CREATE TABLE "config"."execution_state"
(
	"id" serial NOT NULL,
	"system_datetime" timestamp with time zone NOT NULL DEFAULT now(),
	"execution_id" integer NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "config"."execution_state" ADD CONSTRAINT "execution_state_pkey"
	PRIMARY KEY ("id")
;

/* Create Foreign Key Constraints */

ALTER TABLE "config"."execution_state" ADD CONSTRAINT "execution_state_execution_fkey"
	FOREIGN KEY ("execution_id") REFERENCES "config"."execution" ("id") ON DELETE No Action ON UPDATE No Action
;