/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 06-Aug-2020 10:13:40 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS "config"."model_id_seq" CASCADE
;

/* Drop Tables */

DROP TABLE IF EXISTS "config"."model" CASCADE
;

/* Create Tables */

CREATE TABLE "config"."model"
(
	"id" serial NOT NULL,
  "execution_state_id" integer NOT NULL,
  "name" varchar(100) NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "config"."model" ADD CONSTRAINT "model_pkey"
	PRIMARY KEY ("id")
;

/* Create Foreign Key Constraints */

ALTER TABLE "config"."model" ADD CONSTRAINT "model_execution_state_fkey"
	FOREIGN KEY ("execution_state_id") REFERENCES "config"."execution_state" ("id") ON DELETE No Action ON UPDATE No Action
;