/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 06-Aug-2020 10:13:40 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS "curve"."ticker_id_seq" CASCADE
;

/* Drop Tables */

DROP TABLE IF EXISTS "curve"."ticker" CASCADE
;

/* Create Tables */

CREATE TABLE "curve"."ticker"
(
	"execution_state_id" integer NOT NULL,
	"category" varchar(50)	 NOT NULL,
	"id" serial NOT NULL,
	"mth3" varchar(50)	 NULL,
	"yr1" varchar(50)	 NULL,
	"yr2" varchar(50)	 NULL,
	"yr3" varchar(50)	 NULL,
	"yr4" varchar(50)	 NULL,
	"yr5" varchar(50)	 NULL,
	"yr6" varchar(50)	 NULL,
	"yr7" varchar(50)	 NULL,
	"yr8" varchar(50)	 NULL,
	"yr9" varchar(50)	 NULL,
	"yr10" varchar(50)	 NULL,
	"yr15" varchar(50)	 NULL,
	"yr20" varchar(50)	 NULL,
	"yr30" varchar(50)	 NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "curve"."ticker" ADD CONSTRAINT "ticker_pkey"
	PRIMARY KEY ("id")
;

ALTER TABLE "curve"."ticker" ADD CONSTRAINT "ticker_category_check" CHECK (category IN ('sovereign', 'swap', 'cr_swap'))
;

/* Create Foreign Key Constraints */

ALTER TABLE "curve"."ticker" ADD CONSTRAINT "ticker_execution_state_fkey"
	FOREIGN KEY ("execution_state_id") REFERENCES "config"."execution_state" ("id") ON DELETE No Action ON UPDATE No Action
;