/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 06-Aug-2020 10:13:40 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS "curve"."ticker_id_seq" CASCADE
;

/* Drop Tables */

DROP TABLE IF EXISTS "curve"."ticker" CASCADE
;

/* Create Tables */

CREATE TABLE "curve"."ticker"
(
	"execution_state_id" integer NOT NULL,
	"type" varchar(50)	 NOT NULL,
	"id" serial NOT NULL,
	"ticker_3m" varchar(50)	 NULL,
	"ticker_1y" varchar(50)	 NULL,
	"ticker_2y" varchar(50)	 NULL,
	"ticker_3y" varchar(50)	 NULL,
	"ticker_4y" varchar(50)	 NULL,
	"ticker_5y" varchar(50)	 NULL,
	"ticker_6y" varchar(50)	 NULL,
	"ticker_7y" varchar(50)	 NULL,
	"ticker_8y" varchar(50)	 NULL,
	"ticker_9y" varchar(50)	 NULL,
	"ticker_10y" varchar(50)	 NULL,
	"ticker_15y" varchar(50)	 NULL,
	"ticker_20y" varchar(50)	 NULL,
	"ticker_30y" varchar(50)	 NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "curve"."ticker" ADD CONSTRAINT "ticker_pkey"
	PRIMARY KEY ("id")
;

ALTER TABLE "curve"."ticker" ADD CONSTRAINT "ticker_type_check" CHECK (type IN ('sovereign', 'swap', 'cr_swap'))
;

/* Create Foreign Key Constraints */

ALTER TABLE "curve"."ticker" ADD CONSTRAINT "ticker_execution_state_fkey"
	FOREIGN KEY ("execution_state_id") REFERENCES "config"."execution_state" ("id") ON DELETE No Action ON UPDATE No Action
;