/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 06-Aug-2020 10:13:38 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS "arp"."effect_asset_id_seq" CASCADE
;

/* Drop Tables */

DROP TABLE IF EXISTS "arp"."effect_asset" CASCADE
;

/* Create Tables */

CREATE TABLE "arp"."effect_asset"
(
	"position_size" numeric(32,16) NOT NULL,
	"id" serial NOT NULL,
	"strategy_id" integer NOT NULL,
	"asset_id" integer NOT NULL,
	"ndf_code" varchar(50) NOT NULL,
	"spot_code" varchar(50)	NOT NULL,
	"execution_state_id" integer NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "arp"."effect_asset" ADD CONSTRAINT "effect_asset_pkey"
	PRIMARY KEY ("id")
;

ALTER TABLE "arp"."effect_asset" ADD CONSTRAINT "effect_asset_asset_id_strategy_id_key" UNIQUE ("asset_id","strategy_id")
;

/* Create Foreign Key Constraints */

ALTER TABLE "arp"."effect_asset" ADD CONSTRAINT "effect_asset_asset_fkey"
	FOREIGN KEY ("asset_id") REFERENCES "asset"."asset" ("id") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "arp"."effect_asset" ADD CONSTRAINT "effect_asset_effect_fkey"
	FOREIGN KEY ("strategy_id") REFERENCES "arp"."effect" ("strategy_id") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "arp"."effect_asset" ADD CONSTRAINT "effect_asset_execution_state_fkey"
	FOREIGN KEY ("execution_state_id") REFERENCES "config"."execution_state" ("id") ON DELETE No Action ON UPDATE No Action
;