/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 06-Aug-2020 10:13:38 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS "arp"."effect_version_seq" CASCADE
;

/* Drop Tables */

DROP TABLE IF EXISTS "arp"."effect" CASCADE
;

/* Create Tables */

CREATE TABLE "arp"."effect"
(
	"update_imf" boolean NOT NULL,
	"user_date" date NOT NULL,
	"signal_date" date NOT NULL,
	"position_size" numeric(32,16) NOT NULL,
	"risk_weighting" varchar(25) NOT NULL,
	"st_dev_window" integer NOT NULL,
	"bid_ask_spread" integer NOT NULL,
	"carry_type" varchar(50)	 NOT NULL,
	"closing_threshold" numeric(32,16) NOT NULL,
	"day_of_week" integer NOT NULL,
	"frequency" frequency NOT NULL,
	"include_shorts" boolean NOT NULL,
	"interest_rate_cut_off_long" numeric(32,16) NOT NULL,
	"interest_rate_cut_off_short" numeric(32,16) NOT NULL,
	"moving_average_long_term" int NOT NULL,
	"moving_average_short_term" int NOT NULL,
	"is_realtime_inflation_forecast" boolean NOT NULL,
	"trend_indicator" varchar(50)	 NOT NULL,
	"execution_state_id" integer NOT NULL,
	"version" serial NOT NULL,
	"strategy_id" integer NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "arp"."effect" ADD CONSTRAINT "effect_pkey"
	PRIMARY KEY ("strategy_id")
;

ALTER TABLE "arp"."effect" ADD CONSTRAINT "effect_day_of_week_check" CHECK (day_of_week in (0, 1, 2, 3, 4, 5, 6))
;

/* Create Foreign Key Constraints */

ALTER TABLE "arp"."effect" ADD CONSTRAINT "effect_execution_state_fkey"
	FOREIGN KEY ("execution_state_id") REFERENCES "config"."execution_state" ("id") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "arp"."effect" ADD CONSTRAINT "effect_strategy_fkey"
	FOREIGN KEY ("strategy_id") REFERENCES "arp"."strategy" ("id") ON DELETE No Action ON UPDATE No Action
;