/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 06-Aug-2020 10:13:39 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS "arp"."fica_asset_group_id_seq" CASCADE
;

/* Drop Tables */

DROP TABLE IF EXISTS "arp"."fica_asset_group" CASCADE
;

/* Create Tables */

CREATE TABLE "arp"."fica_asset_group"
(
	"id" serial NOT NULL,
	"strategy_id" integer NOT NULL,
	"execution_state_id" integer NOT NULL
)
;
/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "arp"."fica_asset_group" ADD CONSTRAINT "fica_asset_group_pkey"
	PRIMARY KEY ("id")
;

/* Create Foreign Key Constraints */

ALTER TABLE "arp"."fica_asset_group" ADD CONSTRAINT "fica_asset_group_fica_fkey"
	FOREIGN KEY ("strategy_id") REFERENCES "arp"."fica" ("strategy_id") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "arp"."fica_asset_group" ADD CONSTRAINT "fica_asset_group_execution_state_fkey"
	FOREIGN KEY ("execution_state_id") REFERENCES "config"."execution_state" ("id") ON DELETE No Action ON UPDATE No Action
;