/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 06-Aug-2020 10:13:39 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS "arp"."fica_asset_id_seq" CASCADE
;

/* Drop Tables */

DROP TABLE IF EXISTS "arp"."fica_asset" CASCADE
;

/* Create Tables */

CREATE TABLE "arp"."fica_asset"
(
	"asset_id" integer NOT NULL,
	"id" serial NOT NULL,
	"strategy_id" integer NULL,
	"sovereign_ticker_id" integer NOT NULL,
	"swap_ticker_id" integer NOT NULL,
	"swap_cr_ticker_id" integer NOT NULL,
	"execution_state_id" integer NOT NULL
)
;
/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "arp"."fica_asset" ADD CONSTRAINT "fica_asset_pkey"
	PRIMARY KEY ("id")
;

ALTER TABLE "arp"."fica_asset" ADD CONSTRAINT "fica_asset_asset_id_strategy_id_key" UNIQUE ("asset_id","strategy_id")
;

/* Create Foreign Key Constraints */

ALTER TABLE "arp"."fica_asset" ADD CONSTRAINT "fica_asset_asset_fkey"
	FOREIGN KEY ("asset_id") REFERENCES "asset"."asset" ("id") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "arp"."fica_asset" ADD CONSTRAINT "fica_asset_execution_state_fkey"
	FOREIGN KEY ("execution_state_id") REFERENCES "config"."execution_state" ("id") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "arp"."fica_asset" ADD CONSTRAINT "fica_asset_fica_fkey"
	FOREIGN KEY ("strategy_id") REFERENCES "arp"."fica" ("strategy_id") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "arp"."fica_asset" ADD CONSTRAINT "fica_asset_ticker_sovereign_fkey"
	FOREIGN KEY ("sovereign_ticker_id") REFERENCES "curve"."ticker" ("id") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "arp"."fica_asset" ADD CONSTRAINT "fica_asset_ticker_swap_cr_fkey"
	FOREIGN KEY ("swap_cr_ticker_id") REFERENCES "curve"."ticker" ("id") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "arp"."fica_asset" ADD CONSTRAINT "fica_asset_ticker_swap_fkey"
	FOREIGN KEY ("swap_ticker_id") REFERENCES "curve"."ticker" ("id") ON DELETE No Action ON UPDATE No Action
;