/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 06-Aug-2020 10:13:39 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS "arp"."fund_strategy_analytic_id_seq" CASCADE
;

/* Drop Tables */

DROP TABLE IF EXISTS "arp"."fund_strategy_analytic" CASCADE
;

/* Create Tables */

CREATE TABLE "arp"."fund_strategy_analytic"
(
	"id" serial NOT NULL,
	"fund_strategy_id" integer NOT NULL,
	"aggregation_level" varchar(25) NOT NULL,
	"asset_subcategory" varchar(25) NULL,
	"category" varchar(50)	 NOT NULL,
	"subcategory" varchar(50)	 NOT NULL,
	"business_date" date NOT NULL,
	"frequency" frequency NOT NULL,
	"value" numeric(32,16) NOT NULL,
	"execution_state_id" integer NOT NULL
)
;
/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "arp"."fund_strategy_analytic" ADD CONSTRAINT "fund_strategy_analytic_pkey"
	PRIMARY KEY ("id")
;

ALTER TABLE
	"arp"."fund_strategy_analytic"
ADD CONSTRAINT
	"fund_strategy_analytic_fund_strategy_id_asset_subcategory_business_date_category_subcategory_key"
UNIQUE
	("fund_strategy_id","asset_subcategory","business_date", "category","subcategory")
;

ALTER TABLE "arp"."fund_strategy_analytic" ADD CONSTRAINT "fund_strategy_analytic_category_subcategory_check"CHECK (
	(category IN ('performance', 'signal'))
AND
	(CASE
		WHEN category = 'performance'
			THEN subcategory in ('carry', 'spot', 'beta', 'total return', 'correlation','excess return', 'excess return index', 'total return index')
		ELSE subcategory in ('carry', 'momentum', 'value')
	END)
)
;

ALTER TABLE "arp"."fund_strategy_analytic" ADD CONSTRAINT "fund_strategy_analytic_aggregation_level_check"
	CHECK (aggregation_level IN ('asset', 'strategy', 'comparator'))
;

/* Create Foreign Key Constraints */

ALTER TABLE "arp"."fund_strategy_analytic" ADD CONSTRAINT "fund_strategy_analytic_execution_state_fkey"
	FOREIGN KEY ("execution_state_id") REFERENCES "config"."execution_state" ("id") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "arp"."fund_strategy_analytic" ADD CONSTRAINT "fund_strategy_analytic_fund_strategy_fkey"
	FOREIGN KEY ("fund_strategy_id") REFERENCES "arp"."fund_strategy" ("id") ON DELETE No Action ON UPDATE No Action
;