/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 06-Aug-2020 10:13:39 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS "arp"."fund_strategy_asset_weight_id_seq" CASCADE
;

/* Drop Tables */

DROP TABLE IF EXISTS "arp"."fund_strategy_asset_weight" CASCADE
;

/* Create Tables */

CREATE TABLE "arp"."fund_strategy_asset_weight"
(
	"id" serial NOT NULL,
	"fund_strategy_id" integer NOT NULL,
	"asset_id" integer NOT NULL,
	"business_date" date NOT NULL,
	"frequency" frequency NOT NULL,
	"strategy_weight" numeric(32,16) NOT NULL,
	"implemented_weight" numeric(32,16) NULL,
	"execution_state_id" integer NOT NULL
)
;
/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "arp"."fund_strategy_asset_weight" ADD CONSTRAINT "fund_strategy_asset_weight_pkey"
	PRIMARY KEY ("id")
;

ALTER TABLE
	"arp"."fund_strategy_asset_weight"
ADD CONSTRAINT
	"fund_strategy_asset_weight_fund_strategy_id_asset_id_business_date_key"
UNIQUE
	("fund_strategy_id","asset_id", "business_date")
;

/* Create Foreign Key Constraints */

ALTER TABLE "arp"."fund_strategy_asset_weight" ADD CONSTRAINT "fund_strategy_asset_weight_asset_fkey"
	FOREIGN KEY ("asset_id") REFERENCES "asset"."asset" ("id") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "arp"."fund_strategy_asset_weight" ADD CONSTRAINT "fund_strategy_asset_weight_execution_state_fkey"
	FOREIGN KEY ("execution_state_id") REFERENCES "config"."execution_state" ("id") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "arp"."fund_strategy_asset_weight" ADD CONSTRAINT "fund_strategy_asset_weight_fund_strategy_fkey"
	FOREIGN KEY ("fund_strategy_id") REFERENCES "arp"."fund_strategy" ("id") ON DELETE No Action ON UPDATE No Action
;