/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 06-Aug-2020 10:13:39 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS "arp"."fund_strategy_asset_weight_id_seq" CASCADE
;

/* Drop Tables */

DROP TABLE IF EXISTS "arp"."fund_strategy_asset_weight" CASCADE
;

/* Create Tables */

CREATE TABLE "arp"."fund_strategy_asset_weight"
(
	"id" serial NOT NULL,
	"fund_id" int NOT NULL,
	"strategy_asset_weight_id" int NOT NULL,
  "user_id" integer NOT NULL,
	"implemented_weight" numeric(32,16) NOT NULL,
	"system_tstzrange" tstzrange NOT NULL DEFAULT tstzrange(now(), 'infinity', '[)'),
	"execution_state_id" integer NOT NULL
)
;
/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "arp"."fund_strategy_asset_weight" ADD CONSTRAINT "fund_strategy_asset_weight_pkey"
	PRIMARY KEY ("id")
;

/* Create Foreign Key Constraints */

ALTER TABLE "arp"."fund_strategy_asset_weight" ADD CONSTRAINT "fund_strategy_asset_weight_execution_state_fkey"
	FOREIGN KEY ("execution_state_id") REFERENCES "config"."execution_state" ("id") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "arp"."fund_strategy_asset_weight" ADD CONSTRAINT "fund_strategy_asset_weight_fund_strategy_weight_fkey"
	FOREIGN KEY ("fund_id") REFERENCES "fund"."fund" ("id") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "arp"."fund_strategy_asset_weight" ADD CONSTRAINT "fund_strategy_asset_weight_strategy_asset_weight_fkey"
	FOREIGN KEY ("strategy_asset_weight_id") REFERENCES "arp"."strategy_asset_weight" ("id") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "arp"."fund_strategy_asset_weight" ADD CONSTRAINT "fund_strategy_asset_weight_user_id_fkey"
	FOREIGN KEY ("user_id") REFERENCES "auth"."user" ("id") ON DELETE No Action ON UPDATE No Action
;