/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 06-Aug-2020 10:13:39 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS "arp"."fund_strategy_weight_id_seq" CASCADE
;

/* Drop Tables */

DROP TABLE IF EXISTS "arp"."fund_strategy_weight" CASCADE
;

/* Create Tables */

CREATE TABLE "arp"."fund_strategy_weight"
(
	"id" serial NOT NULL,
	"fund_id" integer NOT NULL,
  "strategy_id" integer NOT NULL,
  "set_by_id" varchar NOT NULL,
	"system_tstzrange" tstzrange NOT NULL DEFAULT tstzrange(now(), 'infinity', '[)'),
  "weight" numeric(32,16) NOT NULL,
	"execution_state_id" integer NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "arp"."fund_strategy_weight" ADD CONSTRAINT "fund_strategy_weight_pkey"
	PRIMARY KEY ("id")
;

-- ALTER TABLE "arp"."fund_strategy_weight" ADD CONSTRAINT "fund_strategy_weight_name_system_tstzrange_excl" EXCLUDE USING GIST (name WITH =, system_tstzrange WITH &&)

/* Create Foreign Key Constraints */

ALTER TABLE "arp"."fund_strategy_weight" ADD CONSTRAINT "fund_strategy_weight_execution_state_fkey"
	FOREIGN KEY ("execution_state_id") REFERENCES "config"."execution_state" ("id") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "arp"."fund_strategy_weight" ADD CONSTRAINT "fund_strategy_weight_set_by_id_fkey"
	FOREIGN KEY ("set_by_id") REFERENCES "arp"."app_user" ("id") ON DELETE No Action ON UPDATE No Action
;