/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 06-Aug-2020 10:13:39 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */
DROP SEQUENCE IF EXISTS "arp"."fund_strategy_id_seq" CASCADE
;

/* Drop Tables */

DROP TABLE IF EXISTS "arp"."fund_strategy" CASCADE
;

/* Create Tables */

CREATE TABLE "arp"."fund_strategy"
(
	"fund_id" integer NOT NULL,
	"id" serial NOT NULL,
	"strategy_id" integer NOT NULL,
	"system_datetime" timestamp with time zone NOT NULL DEFAULT now(),
	"weight" numeric(32,16) NOT NULL,
	"output_is_saved" boolean NOT NULL,
	"execution_state_id" integer NOT NULL,
	"app_user_id" varchar(7)	 NOT NULL,
	"python_code_version" varchar(50)	 NOT NULL
)
;
/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "arp"."fund_strategy" ADD CONSTRAINT "fund_strategy_pkey"
	PRIMARY KEY ("id")
;

ALTER TABLE "arp"."fund_strategy" ADD CONSTRAINT "fund_strategy_fund_id_strategy_id_system_datetime_key" UNIQUE ("fund_id","strategy_id","system_datetime")
;

/* Create Foreign Key Constraints */

ALTER TABLE "arp"."fund_strategy" ADD CONSTRAINT "fund_strategy_execution_state_fkey"
	FOREIGN KEY ("execution_state_id") REFERENCES "config"."execution_state" ("id") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "arp"."fund_strategy" ADD CONSTRAINT "fund_strategy_strategy_fkey"
	FOREIGN KEY ("strategy_id") REFERENCES "arp"."strategy" ("id") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "arp"."fund_strategy" ADD CONSTRAINT "fund_strategy_user_fkey"
	FOREIGN KEY ("app_user_id") REFERENCES "arp"."app_user" ("id") ON DELETE No Action ON UPDATE No Action
;