/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 06-Aug-2020 10:13:40 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS "arp"."fx_version_seq" CASCADE
;

/* Drop Tables */

DROP TABLE IF EXISTS "arp"."fx" CASCADE
;

/* Create Tables */

CREATE TABLE "arp"."fx"
(
	"model" varchar(25) NOT NULL,
	"business_tstzrange" tstzrange NOT NULL,
	"signal" varchar(25)	 NOT NULL,
  "currency" varchar(25)	 NOT NULL,
	"response_function" boolean NOT NULL,
	"exposure" numeric(32,16) NOT NULL,
	"momentum_weights" numeric(32,16)[] NOT NULL,
	"transaction_cost" numeric(32,16) NOT NULL,
	"top_crosses" integer NULL,
	"vol_window" integer NULL,
	"value_window" integer NULL,
	"sharpe_cutoff" integer NULL,
	"mean_reversion" integer NULL,
	"historical_base" integer NULL,
	"defensive" boolean NULL,
	"execution_state_id" integer NOT NULL,
	"strategy_id" integer NOT NULL,
	"version" serial NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "arp"."fx" ADD CONSTRAINT "fx_pkey"
	PRIMARY KEY ("strategy_id")
;

ALTER TABLE "arp"."fx" ADD CONSTRAINT "fx_model_check"
  CHECK (model in ('cumo', 'cuca', 'curp', 'dyn hdge', 'ppp all', 'ppp usd', 'ppp curp'))
;


/* Create Foreign Key Constraints */

ALTER TABLE "arp"."fx" ADD CONSTRAINT "fx_execution_state_fkey"
	FOREIGN KEY ("execution_state_id") REFERENCES "config"."execution_state" ("id") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "arp"."fx" ADD CONSTRAINT "fx_strategy_fkey"
	FOREIGN KEY ("strategy_id") REFERENCES "arp"."strategy" ("id") ON DELETE No Action ON UPDATE No Action
;