/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 06-Aug-2020 10:13:39 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS "arp"."fx_asset_id_seq" CASCADE
;

/* Drop Tables */

DROP TABLE IF EXISTS "arp"."fx_asset" CASCADE
;

/* Create Tables */

CREATE TABLE "arp"."fx_asset"
(
	"id" serial NOT NULL,
	"ppp_asset_id" integer NOT NULL,
	"cash_rate_asset_id" integer NOT NULL,
	"currency" char(3) NOT NULL,
	"strategy_id" integer NOT NULL,
	"execution_state_id" integer NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "arp"."fx_asset" ADD CONSTRAINT "fx_asset_pkey"
	PRIMARY KEY ("id")
;

ALTER TABLE "arp"."fx_asset" ADD CONSTRAINT "fx_asset_ppp_asset_id_cash_rate_asset_id_strategy_id_key"
  UNIQUE ("ppp_asset_id", "cash_rate_asset_id", "strategy_id")
;

/* Create Foreign Key Constraints */

ALTER TABLE "arp"."fx_asset" ADD CONSTRAINT "fx_asset_asset_ppp_fkey"
	FOREIGN KEY ("ppp_asset_id") REFERENCES "asset"."asset" ("id") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "arp"."fx_asset" ADD CONSTRAINT "fx_asset_asset_cash_rate_fkey"
	FOREIGN KEY ("cash_rate_asset_id") REFERENCES "asset"."asset" ("id") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "arp"."fx_asset" ADD CONSTRAINT "fx_asset_execution_state_fkey"
	FOREIGN KEY ("execution_state_id") REFERENCES "config"."execution_state" ("id") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "arp"."fx_asset" ADD CONSTRAINT "fx_asset_fx_fkey"
	FOREIGN KEY ("strategy_id") REFERENCES "arp"."fx" ("strategy_id") ON DELETE No Action ON UPDATE No Action
;