/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 06-Aug-2020 10:13:39 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS "arp"."fx_asset_group_id_seq" CASCADE
;

/* Drop Tables */

DROP TABLE IF EXISTS "arp"."fx_asset_group" CASCADE
;

/* Create Tables */

CREATE TABLE "arp"."fx_asset_group"
(
	"strategy_asset_group_id" integer NOT NULL,
	"currency_id" integer NOT NULL,
	"execution_state_id" integer NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "arp"."fx_asset_group" ADD CONSTRAINT "fx_asset_group_pkey"
	PRIMARY KEY ("strategy_asset_group_id")
;

/* Create Foreign Key Constraints */
ALTER TABLE "arp"."fx_asset_group" ADD CONSTRAINT "maven_asset_group_currency_fkey"
	FOREIGN KEY ("currency_id") REFERENCES "lookup"."currency" ("id") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "arp"."fx_asset_group" ADD CONSTRAINT "fx_asset_group_execution_state_fkey"
	FOREIGN KEY ("execution_state_id") REFERENCES "config"."execution_state" ("id") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "arp"."fx_asset_group" ADD CONSTRAINT "fx_asset_group_strategy_asset_group_fkey"
	FOREIGN KEY ("strategy_asset_group_id") REFERENCES "arp"."strategy_asset_group" ("id") ON DELETE No Action ON UPDATE No Action
;