/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 06-Aug-2020 10:13:39 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "arp"."maven_asset_group" CASCADE
;

/* Create Tables */

CREATE TABLE "arp"."maven_asset_group"
(
	"strategy_asset_group_id" integer NOT NULL,
  "execution_state_id" integer NOT NULL,
  "currency_id" integer NOT NULL,
  "is_excess" boolean NOT NULL,
  "asset_weight" numeric(32,16) NOT NULL,
  "transaction_cost" numeric(32,16) NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "arp"."maven_asset_group" ADD CONSTRAINT "maven_asset_group_pkey"
	PRIMARY KEY ("strategy_asset_group_id")
;

/* Create Foreign Key Constraints */
ALTER TABLE "arp"."maven_asset_group" ADD CONSTRAINT "maven_asset_group_execution_state_fkey"
	FOREIGN KEY ("execution_state_id") REFERENCES "config"."execution_state" ("id") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "arp"."maven_asset_group" ADD CONSTRAINT "maven_asset_group_currency_fkey"
	FOREIGN KEY ("currency_id") REFERENCES "lookup"."currency" ("id") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "arp"."maven_asset_group" ADD CONSTRAINT "maven_asset_group_strategy_asset_group_fkey"
	FOREIGN KEY ("strategy_asset_group_id") REFERENCES "arp"."strategy_asset_group" ("id") ON DELETE No Action ON UPDATE No Action
;