/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 06-Aug-2020 10:13:40 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS "arp"."maven_version_seq" CASCADE
;

/* Drop Tables */

DROP TABLE IF EXISTS "arp"."maven" CASCADE
;

/* Create Tables */

CREATE TABLE "arp"."maven"
(
	"er_tr" varchar(25) NOT NULL,
	"frequency" frequency NOT NULL,
	"day_of_week" integer NOT NULL,
	"asset_count" integer NOT NULL,
	"long_cutoff" integer NOT NULL,
	"short_cutoff" integer NOT NULL,
	"val_period_months" integer NOT NULL,
	"val_period_base" integer NOT NULL,
	"momentum_weights" numeric(32,16)[] NOT NULL,
	"volatility_weights" numeric(32,16)[] NOT NULL,
	"execution_state_id" integer NOT NULL,
	"strategy_id" integer NOT NULL,
	"version" serial NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "arp"."maven" ADD CONSTRAINT "maven_pkey"
	PRIMARY KEY ("strategy_id")
;

ALTER TABLE "arp"."maven" ADD CONSTRAINT "maven_day_of_week_check" CHECK (day_of_week in (0, 1, 2, 3, 4, 5, 6))
;

/* Create Foreign Key Constraints */

ALTER TABLE "arp"."maven" ADD CONSTRAINT "maven_execution_state_fkey"
	FOREIGN KEY ("execution_state_id") REFERENCES "config"."execution_state" ("id") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "arp"."maven" ADD CONSTRAINT "maven_strategy_fkey"
	FOREIGN KEY ("strategy_id") REFERENCES "arp"."strategy" ("id") ON DELETE No Action ON UPDATE No Action
;