/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 06-Aug-2020 10:13:39 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS "arp"."maven_asset_id_seq" CASCADE
;

/* Drop Tables */

DROP TABLE IF EXISTS "arp"."maven_asset" CASCADE
;

/* Create Tables */

CREATE TABLE "arp"."maven_asset"
(
	"id" serial NOT NULL,
	"bbg_tr_asset_id" integer NOT NULL,
	"bbg_er_asset_id" integer NOT NULL,
	"cash_asset_id" integer NOT NULL,
  "strategy_id" integer NOT NULL,
  "execution_state_id" integer NOT NULL,
  "asset_category" varchar(25) NOT NULL,
  "asset_subcategory" varchar(25) NOT NULL,
  "currency" char(3) NOT NULL,
  "is_excess" boolean NOT NULL,
  "asset_weight" numeric(32,16) NOT NULL,
  "transaction_cost" numeric(32,16) NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "arp"."maven_asset" ADD CONSTRAINT "maven_asset_pkey"
	PRIMARY KEY ("id")
;

/* Create Foreign Key Constraints */

ALTER TABLE "arp"."maven_asset" ADD CONSTRAINT "maven_asset_asset_bbg_er_fkey"
	FOREIGN KEY ("bbg_tr_asset_id") REFERENCES "asset"."asset" ("id") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "arp"."maven_asset" ADD CONSTRAINT "maven_asset_asset_bbg_tr_fkey"
	FOREIGN KEY ("bbg_er_asset_id") REFERENCES "asset"."asset" ("id") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "arp"."maven_asset" ADD CONSTRAINT "maven_asset_asset_cash_fkey"
	FOREIGN KEY ("cash_asset_id") REFERENCES "asset"."asset" ("id") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "arp"."maven_asset" ADD CONSTRAINT "maven_asset_execution_state_fkey"
	FOREIGN KEY ("execution_state_id") REFERENCES "config"."execution_state" ("id") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "arp"."maven_asset" ADD CONSTRAINT "maven_asset_maven_fkey"
	FOREIGN KEY ("strategy_id") REFERENCES "arp"."maven" ("strategy_id") ON DELETE No Action ON UPDATE No Action
;