/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 06-Aug-2020 10:13:39 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS "arp"."strategy_analytic_id_seq" CASCADE
;

/* Drop Tables */

DROP TABLE IF EXISTS "arp"."strategy_analytic" CASCADE
;

/* Create Tables */

CREATE TABLE "arp"."strategy_analytic"
(
	"id" serial NOT NULL,
	"strategy_id" integer NOT NULL,
	"execution_state_id" integer NOT NULL,
	"category" varchar(50)	 NOT NULL,
	"subcategory" varchar(50)	 NOT NULL,
	"business_date" date NOT NULL,
	"frequency" frequency NOT NULL,
	"value" numeric(32,16) NOT NULL,
	"comparator_name" varchar(50) NOT NULL,
	"comparator_value" varchar(50) NOT NULL
)
;
/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "arp"."strategy_analytic" ADD CONSTRAINT "strategy_analytic_pkey"
	PRIMARY KEY ("id")
;

ALTER TABLE
	"arp"."strategy_analytic"
ADD CONSTRAINT
	"strategy_analytic_strategy_id__business_date_category_subcategory_key"
UNIQUE
	("strategy_id","business_date", "category","subcategory")
;

/* Create Foreign Key Constraints */

ALTER TABLE "arp"."strategy_analytic" ADD CONSTRAINT "strategy_analytic_execution_state_fkey"
	FOREIGN KEY ("execution_state_id") REFERENCES "config"."execution_state" ("id") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "arp"."strategy_analytic" ADD CONSTRAINT "strategy_analytic_strategy_fkey"
	FOREIGN KEY ("strategy_id") REFERENCES "arp"."strategy" ("id") ON DELETE No Action ON UPDATE No Action
;