/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 06-Aug-2020 10:13:40 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS "arp"."times_version_seq" CASCADE
;

/* Drop Tables */

DROP TABLE IF EXISTS "arp"."times" CASCADE
;

/* Create Tables */

CREATE TABLE "arp"."times"
(
	"time_lag" interval NOT NULL,
	"leverage_type" char(1)	 NOT NULL,
	"volatility_window" integer NOT NULL,
	"short_signals" numeric(32,16)[] NOT NULL,
	"long_signals" numeric(32,16)[] NOT NULL,
	"frequency" frequency NOT NULL,
	"day_of_week" integer NOT NULL,
	"execution_state_id" integer NOT NULL,
	"strategy_id" integer NOT NULL,
	"version" serial NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "arp"."times" ADD CONSTRAINT "times_pkey"
	PRIMARY KEY ("strategy_id")
;

ALTER TABLE "arp"."times" ADD CONSTRAINT "times_day_of_week_check" CHECK (day_of_week in (0, 1, 2, 3, 4, 5, 6))
;

ALTER TABLE "arp"."times" ADD CONSTRAINT "times_leverage_type_check" CHECK (leverage_type in ('e', 'n', 'v', 's'))
;

/* Create Foreign Key Constraints */

ALTER TABLE "arp"."times" ADD CONSTRAINT "times_execution_state_fkey"
	FOREIGN KEY ("execution_state_id") REFERENCES "config"."execution_state" ("id") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "arp"."times" ADD CONSTRAINT "times_strategy_fkey"
	FOREIGN KEY ("strategy_id") REFERENCES "arp"."strategy" ("id") ON DELETE No Action ON UPDATE No Action
;