/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 06-Aug-2020 10:13:40 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS "audit"."logged_action_id_seq" CASCADE
;

/* Drop Tables */

DROP TABLE IF EXISTS "audit"."logged_action" CASCADE
;

/* Create Tables */

CREATE TABLE "audit"."logged_action"
(
	"id" bigserial NOT NULL,
	"schema_name" text NOT NULL,
	"table_name" text NOT NULL,
	"session_user_name" text NOT NULL,
	"action_tstamp_tx" time with time zone NOT NULL,
	"action_tstamp_stm" time with time zone NOT NULL,
	"transaction_id" bigint NULL,
	"application_name" text NULL,
	"client_query " text NULL,
	"action" text NOT NULL,
-- 	"row_data" hstore NULL, TODO get hstore extension or refactor this!
-- 	"changed_fields" hstore NULL,
	"statement_only" boolean NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "audit"."logged_action" ADD CONSTRAINT "logged_action_pkey"
	PRIMARY KEY ("id")
;

CREATE INDEX "logged_action_action_tstamp_tx_stm_idx" ON "audit"."logged_action" ("action_tstamp_stm" ASC)
;

CREATE INDEX "logged_action_action_idx" ON "audit"."logged_action" ("action" ASC)
;