/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 06-Aug-2020 10:13:38 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "staging"."asset_analytic" CASCADE
;

/* Create Tables */

CREATE TABLE "staging"."asset_analytic"
(
	"id" serial NOT NULL,
	"ticker" text NOT NULL,
	"analytic_category" text NOT NULL,
	"source" text NOT NULL,
	"value" numeric(32,16) NOT NULL,
	"business_datetime" timestamp with time zone NOT NULL,
	"system_datetime" timestamp with time zone  NOT NULL DEFAULT now()
)
;
