from enum import Enum, auto


class Currency(Enum):
    USD = auto()
    GBP = auto()
    EUR = auto()
    JPY = auto()
    CAD = auto()
    HKD = auto()
    AUD = auto()
    ARS = auto()
    CHF = auto()
    NOK = auto()
    NZD = auto()
    SEK = auto()
    BRL = auto()
    CNY = auto()
    CLP = auto()
    COP = auto()
    CZK = auto()
    EGP = auto()
    HUF = auto()
    IDR = auto()
    ILS = auto()
    INR = auto()
    KRW = auto()
    MYR = auto()
    MXN = auto()
    TWD = auto()
    PLN = auto()
    PHP = auto()
    PEN = auto()
    RON = auto()
    RUB = auto()
    THB = auto()
    TRY = auto()
    ZAR = auto()
    NGN = auto()