/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 12-Mar-2021 10:57:51 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS "auth"."permission_id_seq" CASCADE
;

/* Drop Tables */

DROP TABLE IF EXISTS "auth"."permission" CASCADE
;

/* Create Tables */

CREATE TABLE "auth"."permission"
(
	"id" serial NOT NULL,
	"IUD" text NULL,
	"table_name" text NULL,
	"function_name" text NULL,
	"execution_state_id" integer NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "auth"."permission" ADD CONSTRAINT "permission_pkey"
	PRIMARY KEY ("id")
;

ALTER TABLE "auth"."permission" ADD CONSTRAINT "permission_execution_state_fkey"
	FOREIGN KEY ("execution_state_id") REFERENCES "config"."execution_state" ("id") ON DELETE No Action ON UPDATE No Action
;