/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 12-Mar-2021 10:57:51 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "auth"."role_permission" CASCADE
;

/* Create Tables */

CREATE TABLE "auth"."role_permission"
(
	"role_id" int NOT NULL,
	"permission_id" int NOT NULL,
	"execution_state_id" integer NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "auth"."role_permission" ADD CONSTRAINT "role_permission_pkey"
	PRIMARY KEY ("role_id","permission_id")
;

/* Create Foreign Key Constraints */

ALTER TABLE "auth"."role_permission" ADD CONSTRAINT "role_permission_permission_fkey"
	FOREIGN KEY ("permission_id") REFERENCES "auth"."permission" ("id") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "auth"."role_permission" ADD CONSTRAINT "role_permission_role_fkey"
	FOREIGN KEY ("role_id") REFERENCES "auth"."role" ("id") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "auth"."role_permission" ADD CONSTRAINT "role_permission_execution_state_fkey"
	FOREIGN KEY ("execution_state_id") REFERENCES "config"."execution_state" ("id") ON DELETE No Action ON UPDATE No Action
;