/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 12-Mar-2021 10:57:51 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS "auth"."role_id_seq" CASCADE
;

/* Drop Tables */

DROP TABLE IF EXISTS "auth"."role" CASCADE
;

/* Create Tables */

CREATE TABLE "auth"."role"
(
	"id" serial NOT NULL,
	"name" text NOT NULL,
	"description" text NOT NULL,
	"execution_state_id" integer NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "auth"."role" ADD CONSTRAINT "role_pkey"
	PRIMARY KEY ("id")
;

ALTER TABLE "auth"."role" ADD CONSTRAINT "role_execution_state_fkey"
	FOREIGN KEY ("execution_state_id") REFERENCES "config"."execution_state" ("id") ON DELETE No Action ON UPDATE No Action
;