/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 12-Mar-2021 10:57:51 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS "auth"."user_id_seq" CASCADE
;

/* Drop Tables */

DROP TABLE IF EXISTS "auth"."user" CASCADE
;

/* Create Tables */

CREATE TABLE "auth"."user"
(
	"id" serial NOT NULL,
	"name" text NOT NULL,
	"domino_username" text NOT NULL,
	"email" text NULL,
	"windows_username" text NOT NULL,
	"in_use" boolean NOT NULL,
	"execution_state_id" integer NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "auth"."user" ADD CONSTRAINT "user_pkey"
	PRIMARY KEY ("id")
;

ALTER TABLE "auth"."user" ADD CONSTRAINT "user_execution_state_fkey"
	FOREIGN KEY ("execution_state_id") REFERENCES "config"."execution_state" ("id") ON DELETE No Action ON UPDATE No Action
;