/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 12-Mar-2021 10:57:51 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "auth"."user_role" CASCADE
;

/* Create Tables */

CREATE TABLE "auth"."user_role"
(
	"user_id" int NOT NULL,
	"role_id" int NOT NULL,
	"execution_state_id" integer NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "auth"."user_role" ADD CONSTRAINT "user_role_pkey"
	PRIMARY KEY ("user_id","role_id")
;

/* Create Foreign Key Constraints */

ALTER TABLE "auth"."user_role" ADD CONSTRAINT "user_role_role_fkey"
	FOREIGN KEY ("role_id") REFERENCES "auth"."role" ("id") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "auth"."user_role" ADD CONSTRAINT "user_role_user_fkey"
	FOREIGN KEY ("user_id") REFERENCES "auth"."user" ("id") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "auth"."user_role" ADD CONSTRAINT "user_role_execution_state_fkey"
	FOREIGN KEY ("execution_state_id") REFERENCES "config"."execution_state" ("id") ON DELETE No Action ON UPDATE No Action
;